### ISSUE TITLE
Add LibreSSL support

### ISSUE THREAD

**Issue by klorophatu** [jeff-hughes/shellcaster#28]

**Comment by kotajacob** [comment]
Currently builds with libressl on Void linux for me? `shellcaster` uses the `native-tls` rust package which in turn uses the poorly named `openssl` rust package. To qoute the `openssl` package's readme "This crate provides a safe interface to the popular OpenSSL cryptography library. OpenSSL versions 1.0.1 through 1.1.1 and LibreSSL versions 2.5 through 2.8 are supported."

**Comment by jeff-hughes** [comment]
Thanks for looking into that, @kotajacob. At least according to the [documentation](https://docs.rs/openssl/0.10.30/openssl/), the `openssl` crate works with LibreSSL, although because I don't use LibreSSL myself, I haven't tested it to know for sure.

Note that the documentation also provides some info about environment variables you can use when compiling, which you could try using to point it to the correct library. Beyond that, if it's not working, that's something to take up with the maintainers of the `openssl` crate. It's a dependency of a dependency for `shellcaster`, so it's not something I have direct control over.
