### ISSUE TITLE
Crate not compiling on MacOS

### ISSUE THREAD

**Issue by thunderBiscuit** [jeff-hughes/shellcaster#3]
Not sure why. I am getting error `E0658`. Running `rustc --explain E0658`, I get something about how it's trying to use an unstable feature.

```
If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).
```

Are you on Rust nightly? The rest of the message goes like this:

```
If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:

#![feature(repr128)]

#[repr(u128)] // ok!
enum Foo {
    Bar(u64),
}
```

I will try and update to Rust nightly, but do you have any idea where I'd be supposed to put that piece of code they suggest?

**Comment by thunderBiscuit** [comment]
Attempting to compile using nightly got me much farther. I still got an error message, but I think it was at runtime rather than compile time? My terminal is not displaying the whole error but this is the line I can see:

```
thread 'main' panicked at 'attempt to subtract with overflow', src/ui.rs:401:13
```

Not sure if it will help, but the code in that area is the following:

```rust
let abs_bottom = min(self.n_row,
(self.items.borrow().len() - 1) as i32);
```

**Comment by jeff-hughes** [comment]
Hmm okay, sounds like you've gotten past the compile issues at least, so that's good! I suspect at this point this is just an issue with having a completely empty list. Does it panic for you immediately when it loads, or after you press something?

On mine, I can start it fresh (i.e., empty database) and it doesn't panic, and I can press "a" and it pops up with the "Feed URL:" in the bottom-left corner to input a new feed. But if I try to use the arrow keys to scroll, it will panic. I'll clearly have to add some extra checks for trying to scroll with a 0-length list :)

If you're successfully able to compile, though, I'll call this one closed and add a new issue for the scrolling issue.
